<#
.SYNOPSIS
    One-command local development for mehdisafarzade.dev. See LOCAL_DEV.md.

.DESCRIPTION
    up      Create missing env files (dev-only secrets; existing files are never
            touched), install dependencies if needed, start the portfolio-* dev
            containers, run migrations + the idempotent seed, start the local device
            gate, then the API (:3100) and both Next apps (web :5600, admin :5603).
            On first run it also enrolls this browser in the local gate.
    down    Stop the API, the Next apps, the local gate and the dev containers (data kept).
    status  What's running and on which ports.
    reset   Wipe local data (database, Redis, RabbitMQ, S3, logs) after confirmation.
            Env files and enrolled gate devices are kept.
    init    Only create missing env files (what 'up' does first).

.EXAMPLE
    .\deploy\dev.ps1 up
    .\deploy\dev.ps1 status
    .\deploy\dev.ps1 down
    .\deploy\dev.ps1 reset
#>
[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [ValidateSet('up', 'down', 'status', 'reset', 'init')]
    [string]$Command = 'up',

    # Device name to enroll in the local gate on first run.
    [string]$Device = 'pc',

    # Admin email written into a NEW api/.env.dev (default: git user.email).
    [string]$AdminEmail,

    # Don't open the browser / don't enroll automatically.
    [switch]$NoBrowser,

    # reset: skip the confirmation prompt.
    [switch]$Yes
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repo = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$api = Join-Path $repo 'api'
$fe = Join-Path $repo 'frontend'
$gate = Join-Path (Join-Path $PSScriptRoot 'device-gate') 'gate.ps1'
$stateDir = Join-Path $PSScriptRoot '.dev'
$logDir = Join-Path $stateDir 'logs'
$pidFile = Join-Path $stateDir 'processes.json'
$composeFile = Join-Path $api 'docker-compose.dev.yml'
$yarn = '.yarn/releases/yarn-4.12.0.cjs'
$services = @('db-dev', 'redis-dev', 'rabbitmq-dev', 's3-dev', 'mailpit-dev')

# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

function Write-Step([string]$Text) { Write-Host "`n> $Text" -ForegroundColor Cyan }

function Invoke-Quiet([string]$Dir, [string]$Exe, [string[]]$Arguments, [string]$What) {
    # Native tools print progress on stderr; PS 5.1 would treat that as an error under Stop.
    $prev = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    Push-Location $Dir
    try { $out = & $Exe @Arguments 2>&1 | ForEach-Object { "$_" }; $code = $LASTEXITCODE }
    finally { Pop-Location; $ErrorActionPreference = $prev }
    if ($code -ne 0) {
        Write-Host ($out | Select-Object -Last 25 | Out-String)
        throw "$What failed (exit $code)."
    }
    return $out
}

function Invoke-Yarn([string]$Dir, [string[]]$Arguments, [string]$What) {
    Invoke-Quiet $Dir 'node' (@($yarn) + $Arguments) $What | Out-Null
}

function New-Secret([int]$Bytes) {
    $b = New-Object byte[] $Bytes
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try { $rng.GetBytes($b) } finally { $rng.Dispose() }
    return [Convert]::ToBase64String($b)
}

function New-Passphrase {
    $words = 'amber cobalt delta ember fjord granite harbor island juniper kestrel lumen meadow nimbus orchid prairie quartz'.Split(' ')
    $b = New-Object byte[] 5
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b)
    return (($b[0..3] | ForEach-Object { $words[$_ % $words.Count] }) -join '-') + '-' + (100 + ($b[4] % 900))
}

function Write-NewFile([string]$Path, [string]$Content) {
    if (Test-Path $Path) { Write-Host "  kept     $($Path.Substring($repo.Length + 1)) (exists, not touched)"; return $false }
    # UTF-8 without BOM, LF endings (dotenv and Next read it fine either way).
    [IO.File]::WriteAllText($Path, ($Content -replace "`r", ''), (New-Object System.Text.UTF8Encoding($false)))
    Write-Host "  created  $($Path.Substring($repo.Length + 1))"
    return $true
}

function Initialize-EnvFiles {
    Write-Step 'Env files (created only when missing, dev-only secrets)'
    $email = $AdminEmail
    if (-not $email) {
        try { $email = (& git -C $repo config user.email 2>$null) } catch { $email = $null }
    }
    if (-not $email) { $email = 'admin@localhost.test' }
    $date = (Get-Date).ToString('yyyy-MM-dd')
    # Shared between api/.env.dev and web/.env.local (must be equal on both sides).
    $revalidateSecret = New-Secret 48
    $previewSecret = New-Secret 48

    $apiEnv = @"
# Local development only. Generated by deploy/dev.ps1 on $date. Never commit (git-ignored).
NODE_ENV=development
SERVER_PORT=3100
LOG_DIR=./logs
LOG_LEVEL=debug

# portfolio-* dev containers (docker-compose.dev.yml)
DATABASE_URL=postgresql://portfolio:portfolio@localhost:5436/portfolio
REDIS_URL=redis://localhost:6382/1
REDIS_KEY_PREFIX=pf:
RABBITMQ_URL=amqp://portfolio:portfolio@localhost:5673/portfolio

WEB_ORIGIN=http://localhost:5600
ADMIN_ORIGIN=https://localhost:8443
CORS_EXTRA_ORIGINS=
# Peers trusted to send X-Admin-Device / X-Real-IP. Docker Desktop delivers the local gate's requests from loopback.
ADMIN_TRUSTED_SOURCES=127.0.0.1,::1

# SeaweedFS S3 (portfolio-s3-dev); credentials from dev/seaweedfs-s3.json
S3_REGION=eu-central-1
S3_BUCKET=portfolio-media-dev
S3_ACCESS_KEY_ID=portfolio
S3_SECRET_ACCESS_KEY=portfolio-dev-secret
S3_ENDPOINT=http://localhost:9002
S3_FORCE_PATH_STYLE=true

# Mailpit (portfolio-mailpit-dev): every email lands at http://localhost:8026
MAIL_HOST=localhost
MAIL_PORT=1026
MAIL_SECURE=false
MAIL_USER=
MAIL_PASS=
MAIL_FROM="Mehdi Safarzade <no-reply@mehdisafarzade.dev>"
CONTACT_NOTIFY_TO=contact@mehdisafarzade.dev

IP_HASH_PEPPER=$(New-Secret 48)

# API -> web on-demand revalidation + draft previews (same secrets as web/.env.local)
WEB_REVALIDATE_URLS=http://localhost:5600/api/revalidate
REVALIDATE_SECRET=$revalidateSecret
PREVIEW_SECRET=$previewSecret

ADMIN_JWT_SECRET=$(New-Secret 48)
ADMIN_PENDING_JWT_SECRET=$(New-Secret 48)
TOTP_ENC_KEY=$(New-Secret 32)

# Seed (idempotent): your local admin. Sign in with these, then set up TOTP.
SEED_ADMIN_EMAIL=$email
SEED_ADMIN_PASSWORD=$(New-Passphrase)
"@
    $webEnv = @"
# Local development only. Generated by deploy/dev.ps1 on $date (git-ignored).
NEXT_PUBLIC_API_URL=http://localhost:3100/v1
NEXT_PUBLIC_SITE_URL=http://localhost:5600
# Cloudflare's always-pass Turnstile test key
NEXT_PUBLIC_TURNSTILE_SITE_KEY=1x00000000000000000000AA
NEXT_PUBLIC_CF_BEACON_TOKEN=
INTERNAL_API_URL=
# must equal api/.env.dev
REVALIDATE_SECRET=$revalidateSecret
PREVIEW_SECRET=$previewSecret
"@
    $adminEnv = @"
# Local development only. Generated by deploy/dev.ps1 on $date (git-ignored).
# Open the admin via the local gate: https://localhost:8443
NEXT_PUBLIC_API_URL=http://localhost:3100/v1
NEXT_PUBLIC_ADMIN_URL=https://localhost:8443
NEXT_PUBLIC_SITE_URL=http://localhost:5600
INTERNAL_API_URL=http://localhost:3100/v1
"@
    $script:createdApiEnv = Write-NewFile (Join-Path $api '.env.dev') $apiEnv
    $null = Write-NewFile (Join-Path (Join-Path (Join-Path $fe 'apps') 'web') '.env.local') $webEnv
    $null = Write-NewFile (Join-Path (Join-Path (Join-Path $fe 'apps') 'admin') '.env.local') $adminEnv
}

function Get-Processes {
    if (-not (Test-Path $pidFile)) { return @() }
    $raw = Get-Content $pidFile -Raw
    if (-not $raw -or -not $raw.Trim()) { return @() }
    return @(@($raw | ConvertFrom-Json) | Where-Object { $null -ne $_ -and $_.PSObject.Properties['pid'] })
}

function Test-Alive([int]$ProcessId) {
    return $null -ne (Get-Process -Id $ProcessId -ErrorAction SilentlyContinue)
}

function Stop-Tree([int]$ProcessId) {
    if (-not (Test-Alive $ProcessId)) { return }
    if ($env:OS -eq 'Windows_NT') {
        & taskkill.exe /PID $ProcessId /T /F 2>&1 | Out-Null
    } else {
        Stop-Process -Id $ProcessId -Force -ErrorAction SilentlyContinue
    }
}

function Start-Background([string]$Name, [string]$Dir, [string[]]$Arguments) {
    $out = Join-Path $logDir "$Name.log"
    $err = Join-Path $logDir "$Name.err.log"
    $node = (Get-Command node).Source
    $p = Start-Process -FilePath $node -ArgumentList $Arguments -WorkingDirectory $Dir -PassThru `
        -WindowStyle Hidden -RedirectStandardOutput $out -RedirectStandardError $err
    return [pscustomobject]@{ name = $Name; pid = $p.Id; log = $out }
}

function Get-HttpStatus([string]$Url) {
    try {
        if ($PSVersionTable.PSVersion.Major -ge 6) {
            $r = Invoke-WebRequest -Uri $Url -Method Get -TimeoutSec 3 -SkipCertificateCheck -MaximumRedirection 0 -SkipHttpErrorCheck -ErrorAction Stop
            return [int]$r.StatusCode
        }
        # Windows PowerShell 5.1: curl.exe ships with Windows 10+ and handles the self-signed gate cert.
        $code = & curl.exe -sk -o NUL -w '%{http_code}' --max-time 3 $Url 2>$null
        return [int]$code
    } catch {
        return 0
    }
}

function Wait-Http([string]$Name, [string]$Url, [int[]]$Ok, [int]$TimeoutSec, [string]$Log) {
    $deadline = (Get-Date).AddSeconds($TimeoutSec)
    while ((Get-Date) -lt $deadline) {
        $code = Get-HttpStatus $Url
        if ($Ok -contains $code) { Write-Host "  ready    $Name  $Url ($code)"; return }
        Start-Sleep -Seconds 2
    }
    Write-Host "  NOT READY $Name ($Url). Last lines of $Log :" -ForegroundColor Yellow
    if ($Log -and (Test-Path $Log)) { Get-Content $Log -Tail 20 | ForEach-Object { Write-Host "    $_" } }
    $errLog = $Log -replace '\.log$', '.err.log'
    if ($Log -and (Test-Path $errLog)) { Get-Content $errLog -Tail 20 | ForEach-Object { Write-Host "    $_" } }
    throw "$Name did not become ready within $TimeoutSec s."
}

function Get-BusyPorts([int[]]$Ports) {
    $busy = @()
    foreach ($port in $Ports) {
        $c = New-Object System.Net.Sockets.TcpClient
        try {
            $ar = $c.BeginConnect('127.0.0.1', $port, $null, $null)
            if ($ar.AsyncWaitHandle.WaitOne(300) -and $c.Connected) { $busy += $port }
        } catch { } finally { $c.Close() }
    }
    return $busy
}

function Assert-Tools {
    foreach ($t in @('docker', 'node', 'git')) {
        if (-not (Get-Command $t -ErrorAction SilentlyContinue)) { throw "'$t' is not on PATH." }
    }
    $prev = $ErrorActionPreference; $ErrorActionPreference = 'Continue'
    & docker info 2>&1 | Out-Null
    $dockerOk = ($LASTEXITCODE -eq 0)
    $ErrorActionPreference = $prev
    if (-not $dockerOk) { throw 'Docker is not running. Start Docker Desktop and try again.' }
    $major = [int]((& node -v).TrimStart('v').Split('.')[0])
    if ($major -lt 22) { throw "Node 22+ is required (found $(& node -v))." }
}

# ---------------------------------------------------------------------------
# commands
# ---------------------------------------------------------------------------

function Invoke-Up {
    Assert-Tools
    foreach ($d in @($stateDir, $logDir)) { if (-not (Test-Path $d)) { New-Item -ItemType Directory -Path $d | Out-Null } }
    $running = @(Get-Processes | Where-Object { Test-Alive $_.pid })
    if ($running.Count -gt 0) {
        Write-Host "Already running ($(($running | ForEach-Object { $_.name }) -join ', ')). Use '.\deploy\dev.ps1 status' or 'down' first." -ForegroundColor Yellow
        return
    }

    $busy = @(Get-BusyPorts @(3100, 5600, 5603))
    if ($busy.Count -gt 0) {
        throw "Port(s) $($busy -join ', ') already in use by something dev.ps1 didn't start (an API or 'next dev' from another terminal?). Stop it first; dev.ps1 won't kill processes it doesn't own."
    }

    Initialize-EnvFiles

    Write-Step 'Dependencies'
    if (-not (Test-Path (Join-Path $api 'node_modules'))) { Invoke-Yarn $api @('install') 'api: yarn install'; Write-Host '  installed api' }
    else { Write-Host '  api ok' }
    if (-not (Test-Path (Join-Path $fe 'node_modules'))) { Invoke-Yarn $fe @('install') 'frontend: yarn install'; Write-Host '  installed frontend' }
    else { Write-Host '  frontend ok' }

    Write-Step 'Dev containers (portfolio-*)'
    Invoke-Quiet $api 'docker' (@('compose', '-f', $composeFile, 'up', '-d', '--wait') + $services) 'docker compose up' | Out-Null
    Write-Host "  up       $($services -join ', ')"

    Write-Step 'Database: migrations + seed (idempotent)'
    Invoke-Yarn $api @('prisma:dev:deploy') 'prisma migrate deploy'
    Write-Host '  migrated'
    Invoke-Yarn $api @('prisma:dev:seed') 'seed'
    Write-Host '  seeded'

    Write-Step 'Local device gate (https://localhost:8443)'
    Invoke-Quiet $repo 'powershell' @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $gate, 'up', '-Target', 'local') 'gate up' | Out-Null
    Write-Host '  up'

    Write-Step 'API + Next apps'
    $procs = @()
    $procs += Start-Background 'api' $api @($yarn, 'dotenv', '-e', '.env.dev', '--', 'nest', 'start', '--watch')
    $procs += Start-Background 'next' $fe @($yarn, 'dev')
    ConvertTo-Json -InputObject @($procs) | Set-Content -Path $pidFile -Encoding UTF8
    Wait-Http 'api' 'http://localhost:3100/v1/health' @(200) 120 (Join-Path $logDir 'api.log')
    Wait-Http 'web' 'http://localhost:5600/en' @(200) 180 (Join-Path $logDir 'next.log')
    Wait-Http 'admin' 'http://localhost:5603/login' @(200) 180 (Join-Path $logDir 'next.log')
    Wait-Http 'gate' 'https://localhost:8443/' @(404, 200, 307) 30 ''

    $listing = Invoke-Quiet $repo 'powershell' @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $gate, 'list', '-Target', 'local') 'gate list'
    $hasDevice = @($listing | Where-Object { $_ -match '\bOK\s*$' }).Count -gt 0
    if (-not $hasDevice) {
        if ($NoBrowser) {
            Write-Host "`nNo browser is enrolled in the local gate yet. Run:" -ForegroundColor Yellow
            Write-Host "  .\deploy\device-gate\gate.ps1 enroll -Device $Device -Target local"
        } else {
            Write-Step "Enrolling this browser as '$Device' (a one-time link opens in your default browser)"
            & powershell -NoProfile -ExecutionPolicy Bypass -File $gate enroll -Device $Device -Target local -TimeoutSec 180
        }
    }

    Write-Host ''
    Write-Host 'Local stack is up:' -ForegroundColor Green
    Write-Host '  web      http://localhost:5600'
    Write-Host '  admin    https://localhost:8443   (through the device gate; accept the self-signed cert once)'
    Write-Host '  api      http://localhost:3100/v1'
    Write-Host '  mail     http://localhost:8026    (Mailpit)'
    Write-Host '  rabbitmq http://localhost:15673   (portfolio / portfolio)'
    Write-Host "  logs     $logDir"
    if ($script:createdApiEnv) {
        Write-Host ''
        Write-Host 'First run: sign in with SEED_ADMIN_EMAIL / SEED_ADMIN_PASSWORD from api/.env.dev, then set up TOTP.' -ForegroundColor Yellow
    }
}

function Invoke-Down {
    Write-Step 'Stopping API + Next apps'
    foreach ($p in Get-Processes) {
        if (Test-Alive $p.pid) { Stop-Tree $p.pid; Write-Host "  stopped  $($p.name) (pid $($p.pid))" }
    }
    if (Test-Path $pidFile) { Remove-Item $pidFile -Force }
    Write-Step 'Stopping the local gate and dev containers (data kept)'
    Invoke-Quiet $repo 'powershell' @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $gate, 'down', '-Target', 'local') 'gate down' | Out-Null
    Invoke-Quiet $api 'docker' @('compose', '-f', $composeFile, 'stop') 'docker compose stop' | Out-Null
    Write-Host '  stopped'
}

function Invoke-Status {
    Write-Host 'Containers:'
    $prev = $ErrorActionPreference; $ErrorActionPreference = 'Continue'
    $rows = & docker ps -a --filter 'name=portfolio-' --format '{{.Names}}|{{.Status}}|{{.Ports}}' 2>$null
    $ErrorActionPreference = $prev
    if (-not $rows) { Write-Host '  (none)' }
    foreach ($r in @($rows)) {
        $c = "$r".Split('|')
        $ports = ($c[2] -replace '127\.0\.0\.1:', '' -replace '->\d+/tcp', '' -replace ', \[::\]:\d+', '')
        Write-Host ('  {0,-26} {1,-28} {2}' -f $c[0], $c[1], $ports)
    }
    Write-Host 'Processes:'
    $procs = @(Get-Processes)
    if ($procs.Count -eq 0) { Write-Host '  (none started by dev.ps1)' }
    foreach ($p in $procs) {
        $state = 'stopped'
        if (Test-Alive $p.pid) { $state = 'running' }
        Write-Host ('  {0,-6} pid {1,-7} {2}' -f $p.name, $p.pid, $state)
    }
    Write-Host 'Endpoints:'
    $checks = [ordered]@{
        'api   http://localhost:3100/v1/health' = 'http://localhost:3100/v1/health'
        'web   http://localhost:5600/en'        = 'http://localhost:5600/en'
        'admin http://localhost:5603/login'     = 'http://localhost:5603/login'
        'gate  https://localhost:8443/'         = 'https://localhost:8443/'
        'mail  http://localhost:8026/'          = 'http://localhost:8026/'
    }
    foreach ($k in $checks.Keys) {
        $code = Get-HttpStatus $checks[$k]
        $label = "$code"
        if ($code -eq 0) { $label = 'down' }
        if ($k -like 'gate*' -and $code -eq 404) { $label = '404 (up; gate blocks unenrolled requests)' }
        Write-Host ('  {0,-40} {1}' -f $k, $label)
    }
}

function Invoke-Reset {
    Write-Host 'This wipes ALL local dev data: the portfolio dev database (incl. your local admin user and TOTP),'
    Write-Host 'Redis, RabbitMQ, local S3 media and dev.ps1 logs. Env files and enrolled gate devices are kept.'
    if (-not $Yes) {
        $answer = Read-Host "Type 'reset' to continue"
        if ($answer -ne 'reset') { Write-Host 'Cancelled. Nothing was changed.'; return }
    }
    Invoke-Down
    Write-Step 'Removing dev containers and their volumes'
    Invoke-Quiet $api 'docker' @('compose', '-f', $composeFile, 'down', '-v') 'docker compose down -v' | Out-Null
    if (Test-Path $logDir) { Remove-Item -Recurse -Force $logDir }
    Write-Host '  done. Run .\deploy\dev.ps1 up to start fresh (the seed recreates your admin; set up TOTP again).'
}

switch ($Command) {
    'up' { Invoke-Up }
    'down' { Invoke-Down }
    'status' { Invoke-Status }
    'reset' { Invoke-Reset }
    'init' { Initialize-EnvFiles }
}
